config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'
  resources :rss_articles, only: %i[index destroy]
  resources :rss_sources
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rss_article.rb
# frozen_string_literal: true

# Article Entity
class RssArticle < ApplicationRecord
  belongs_to :rss_source
  validates :rss_source_id, presence: true, numericality: true
  validates :published_at, presence: true, date: true
  validates :title, presence: true, format: { with: /[a-zA-Z0-9_]/ }, length: { maximum: 255 }
  validates :url, presence: true, url: true, uniqueness: true
end

app/models/rss_source.rb
# frozen_string_literal: true

# RssSource Entity
class RssSource < ApplicationRecord
  has_many :rss_articles, dependent: :destroy
  validates :name, presence: true, format: { with: /[a-zA-Z0-9_]/ }, length: { in: 3..255 }
  validates :url, presence: true, url: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Home Controller
class HomeController < ApplicationController
  def index; end
end

app/controllers/rss_articles_controller.rb
# frozen_string_literal: true

# Articles controller
class RssArticlesController < ApplicationController
  before_action :set_rss_article, only: [:destroy]

  # GET /rss_articles
  # GET /rss_articles.json
  def index
    @rss_articles = RssArticle.order('rss_articles.published_at DESC').all
  end

  # DELETE /rss_articles/1
  # DELETE /rss_articles/1.json
  def destroy
    @rss_article.destroy
    respond_to do |format|
      format.html { redirect_to rss_articles_url, notice: 'Rss article was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_rss_article
    @rss_article = RssArticle.find(params[:id])
  end
end

app/controllers/rss_sources_controller.rb
# frozen_string_literal: true

# Rss Sources Controller
class RssSourcesController < ApplicationController
  before_action :set_rss_source, only: [:show, :edit, :update, :destroy]

  # GET /rss_sources
  # GET /rss_sources.json
  def index
    @rss_sources = RssSource.all
  end

  # GET /rss_sources/1
  # GET /rss_sources/1.json
  def show
  end

  # GET /rss_sources/new
  def new
    @rss_source = RssSource.new
  end

  # GET /rss_sources/1/edit
  def edit
  end

  # POST /rss_sources
  # POST /rss_sources.json
  def create
    @rss_source = RssSource.new(rss_source_params)

    respond_to do |format|
      if @rss_source.save
        format.html { redirect_to @rss_source, notice: 'Rss source was successfully created.' }
        format.json { render :show, status: :created, location: @rss_source }
      else
        format.html { render :new }
        format.json { render json: @rss_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rss_sources/1
  # PATCH/PUT /rss_sources/1.json
  def update
    respond_to do |format|
      if @rss_source.update(rss_source_params)
        format.html { redirect_to @rss_source, notice: 'Rss source was successfully updated.' }
        format.json { render :show, status: :ok, location: @rss_source }
      else
        format.html { render :edit }
        format.json { render json: @rss_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rss_sources/1
  # DELETE /rss_sources/1.json
  def destroy
    @rss_source.destroy
    respond_to do |format|
      format.html { redirect_to rss_sources_url, notice: 'Rss source was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rss_source
      @rss_source = RssSource.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rss_source_params
      params.require(:rss_source).permit(:name, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rss_articles_helper.rb
module RssArticlesHelper
end

app/helpers/rss_sources_helper.rb
module RssSourcesHelper
end

app/views/home/index.html.erb
<div class="inner home">
  <header>
    <h1>RSS on Rails</h1>
    <h2>Your Simple RSS Feed Reader</h2>
  </header>
  <section class="tiles">
    <article class="style1">
      <span class="image">
        <%= image_tag "pic07.jpg" %>
      </span>
      <a href="/rss_sources">
        <h2>Manage Your Feeds</h2>
        <h3></h3>
        <div class="content">
          <p></p>
        </div>
      </a>
      </article>
      <article class="style2">
        <span class="image">
          <%= image_tag "pic01.jpg" %>
        </span>
        <a href="/rss_articles">
          <h2>View Articles</h2>
          <h3></h3>
          <div class="content">
            <p></p>
          </div>
        </a>
        </article>
  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RSS On Rails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper">
      <div id="main">
        <div class="inner">
            <%= link_to "Home", root_path %>
            <%= yield %>
          </div>
        </div>
      </div>
  </body>
</html>

app/views/rss_articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Source</th>
      <th>Title</th>
      <th>Published</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @rss_articles.each do |rss_article| %>
      <tr>
        <td><%= rss_article.rss_source.name %></td>
        <td>
          <a href="<%= rss_article.url %>" target="_blank" rel="noopener noreferrer">
            <%= rss_article.title %>
          </a>
        </td>
        <td><%= rss_article.published_at =%></td>
        <td><%= link_to 'Delete', rss_article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rss_sources/_form.html.erb
<%= form_with(model: rss_source, local: true) do |form| %>
  <% if rss_source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rss_source.errors.count, "error") %> prohibited this rss_source from being saved:</h2>

      <ul>
      <% rss_source.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rss_sources/edit.html.erb
<h1>Editing Rss Source</h1>

<%= render 'form', rss_source: @rss_source %>

<%= link_to 'Show', @rss_source %> |
<%= link_to 'Back', rss_sources_path %>

app/views/rss_sources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rss Sources</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rss_sources.each do |rss_source| %>
      <tr>
        <td><%= rss_source.name %></td>
        <td><%= rss_source.url %></td>
        <td><%= link_to 'Show', rss_source %></td>
        <td><%= link_to 'Edit', edit_rss_source_path(rss_source) %></td>
        <td><%= link_to 'Delete', rss_source, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Rss Source', new_rss_source_path %>

app/views/rss_sources/new.html.erb
<h1>Add New Rss Source</h1>

<%= render 'form', rss_source: @rss_source %>

<%= link_to 'Back', rss_sources_path %>

app/views/rss_sources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @rss_source.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @rss_source.url %>
</p>

<%= link_to 'Edit', edit_rss_source_path(@rss_source) %> |
<%= link_to 'Back', rss_sources_path %>